#SERVER
SERVER_PORT: 8089
ACTIVE_PROFILE: dev


#DATASOURSE
POSTGRES_USER: sidof
POSTGRES_PASSWORD: sidof1/@
POSTGRES_DATABASE: bankdb
POSTGRES_URL: jdbc:postgresql://${HOST_SERVER}:${POSTGRES_PORT_MAPPER}/${POSTGRES_DATABASE}
POSTGRES_PORT: 5432
POSTGRES_PORT_MAPPER: 5334
DB_HOST: localhost


#EMAIL CONFIG
EMAIL_HOST: localhost
EMAIL_PORT: 1025
EMAIL_ID: sidofdountio@gmail.com
EMAIL_PASSWORD: sa

COMPANY_EMAIL: afrilandsidof@gmail.com
SECRETKEY: 3521a409ec66d38296f0acc5f264e1541e26336b251bf48d6969e0eabca486cd9eb35f2c30d7eebaebad4867b58cb9f8188714138e05e71e8a173b711eed1768
EXPIRATION: 86400000

#FRONTEND
HOST_SERVER: localhost
ANGULAR_PORT: 30006
VERIFY_EMAIL_HOST: http://localhost${SERVER_PORT}
ACTIVATION_URL: http://${HOST_SERVER}:${ANGULAR_PORT}/activation-account
CUSTOMER_ORDER_URL: http://${HOST_SERVER}:${ANGULAR_PORT}/service/customer-invoice
ORIGIN: http://localhost:8088/api/v1/fast-gaz